#!/usr/bin/env python
"""
Generate per-project task snippets for MkDocs.

For each project slug, this script:
- Calls the GitHub Issues API for Manitec/Manitec-Tasks
- Filters open issues with label `project: <slug>`
- Writes meta/tasks-<slug>.md containing a small "Open tasks" section

Intended to be run in CI before `mkdocs build`, using GITHUB_TOKEN.
"""

import os
import sys
import textwrap
from typing import List, Dict, Any

import requests

OWNER = "Manitec"
TASKS_REPO = "Manitec-Tasks"
GITHUB_API = "https://api.github.com"
TOKEN = os.getenv("GITHUB_TOKEN")

# Project slugs must match the `project:<slug>` labels you put on issues
PROJECT_SLUGS = [
    "manibot",
    "hexbot",
    "banjoshire",
    "chatbot",
    "joesfaves",
    "manitec-apps",
    "ebbinor",
    "mailserver",
    "control-hub",
    "command-hub",
    "manitec-dashboard",
    "manitec-site",
]

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "tasks")  # meta/tasks/
os.makedirs(OUTPUT_DIR, exist_ok=True)


def github_headers() -> Dict[str, str]:
    if not TOKEN:
        print("WARNING: GITHUB_TOKEN not set; writing empty snippets.", file=sys.stderr)
        return {}
    return {
        "Authorization": f"Bearer {TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def fetch_issues_for_project(slug: str) -> List[Dict[str, Any]]:
    """Fetch open issues with label `project:<slug>` for this repo."""
    if not TOKEN:
        return []
    url = f"{GITHUB_API}/repos/{OWNER}/{TASKS_REPO}/issues"
    params = {
        "state": "open",
        "labels": f"project: {slug}",
        "per_page": 100,
    }
    resp = requests.get(url, headers=github_headers(), params=params, timeout=10)
    if resp.status_code == 404:
        print(f"INFO: {TASKS_REPO} not found or no access for '{slug}' — writing empty snippet.", file=sys.stderr)
        return []
    if resp.status_code == 403:
        print(f"INFO: 403 Forbidden for '{slug}' — token may lack issues:read — writing empty snippet.", file=sys.stderr)
        return []
    if resp.status_code != 200:
        raise RuntimeError(
            f"GitHub API error {resp.status_code} for project '{slug}': {resp.text}"
        )
    issues = resp.json()
    # Filter out pull requests (GitHub returns PRs in the /issues API)
    return [i for i in issues if "pull_request" not in i]


def make_snippet(slug: str, issues: List[Dict[str, Any]]) -> str:
    """Build the markdown snippet body for one project."""
    header = f"### Open tasks for `{slug}`\n"
    if not issues:
        body = "\n_No open tasks linked to this project._\n"
        return header + body

    lines = [header, ""]
    for issue in issues:
        number = issue.get("number")
        title = issue.get("title", "Untitled").strip()
        url = issue.get("html_url")
        lines.append(f"- [#{number} \u2013 {title}]({url})")

    lines.append("")  # trailing newline
    return "\n".join(lines)


def write_snippet(slug: str, content: str) -> None:
    """Write meta/tasks-<slug>.md with an auto-generated warning."""
    path = os.path.join(OUTPUT_DIR, f"tasks-{slug}.md")
    header = textwrap.dedent(
        """\
        <!-- AUTO-GENERATED FILE: do not edit by hand.
             Generated by meta/generate_task_fragments.py -->

        """
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(content)
    print(f"Wrote {path}")


def main() -> None:
    for slug in PROJECT_SLUGS:
        try:
            issues = fetch_issues_for_project(slug)
            snippet = make_snippet(slug, issues)
            write_snippet(slug, snippet)
        except Exception as e:
            print(f"Error generating tasks for '{slug}': {e}", file=sys.stderr)
            # Write empty snippet so build doesn't fail on missing include
            write_snippet(slug, make_snippet(slug, []))


if __name__ == "__main__":
    main()
